### ISSUE TITLE
FromIterator for Vec

### ISSUE THREAD

**Issue by burrbull** [japaric/heapless#36]
Is it possible to implement `IntoIterator` for `Vec` and maybe other?
It is needed for `.collect()`.

**Comment by XOSplicer** [comment]
`IntoIterator<Item = &'a T>` and `IntoIterator<Item = &'a mut T>` are already implemented for `Vec<T, ..>`. However it might indeed be useful to implement `IntoIterator<Item = T>` which would have move semantics while iterating over the vector. This would gradually move all elements out of the vector and could drop the underlaying buffer once the collection is empty.

The trait that needs to be implemented to allow the usage of `.collect<heapless::Vec<T, ...>>` is `FromIterator`. It is currently not implemented for `Vec<T, ...>`. It can however in general by unsafe to collect an iterator with arbitrary many items into an Vec, which has a fixed size, statically allocated buffer for storage. As a user of the `collect` method you would need to specify how large this buffer is. But since `from_iter()` does not return a result, we could `panic!` if the buffer runs full, or simply drop al extra items.

**Comment by burrbull** [comment]
Yes, you are right. I mean `FromIterator`

**Comment by XOSplicer** [comment]
closed in #38 and #39
